fiorella-mansilla/kuna_backend

src/main/java/com/kuna_backend/entities/client.java
src/main/java/com/kuna_backend/entities/enums/Color.java
src/main/java/com/kuna_backend/entities/enums/Size.java
src/main/java/com/kuna_backend/entities/item.java
src/main/java/com/kuna_backend/entities/order.java
src/main/java/com/kuna_backend/entities/user.java

- Client Entity created
- Item Entity created 
- Enums of Color and Size created for Item class
- Order Entity created
- User Entity created

T 42/create entities

---

src/main/java/com/kuna_backend/KunaBackendApplication.java
src/main/java/com/kuna_backend/controllers/ClientController.java
src/main/java/com/kuna_backend/controllers/ClientNotFoundException.java
src/main/java/com/kuna_backend/controllers/ElementNotFoundException.java
src/main/java/com/kuna_backend/controllers/ItemController.java
src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/controllers/UserController.java
src/main/java/com/kuna_backend/dao/ClientDaoService.java
src/main/java/com/kuna_backend/dao/ItemDaoService.java
src/main/java/com/kuna_backend/dao/OrderDaoService.java
src/main/java/com/kuna_backend/dao/UserDaoService.java
src/main/java/com/kuna_backend/entities/Client.java
src/main/java/com/kuna_backend/entities/Item.java
src/main/java/com/kuna_backend/entities/Order.java
src/main/java/com/kuna_backend/entities/User.java

- Client, Item, Order and User Controllers created 
- Client, Item, Order and User Dao's created 
- REST API Endpoints Implemented for Client, Item, Order and User
- With GET, POST, PUT, and DELETE Methods implemented

T-43/ Create Endpoints

---

src/main/java/com/kuna_backend/repositories/ClientRepository.java
src/main/java/com/kuna_backend/repositories/ItemRepository.java
src/main/java/com/kuna_backend/repositories/OrderRepository.java
src/main/java/com/kuna_backend/repositories/UserRepository.java
src/main/resources/application.properties

- Created CRUD Repositories for all Entities with Spring Data JPA
- Added an annotation on application.properties

T 49  - JPA Repositories

---

src/main/java/com/kuna_backend/services/ClientService.java
src/main/java/com/kuna_backend/services/ItemService.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/UserService.java

Created services as a middle layer between repositories and controllers.
Used @Transactional annotation for methods that are executed during transactions.

T-50 / Services created for all classes

---

build.gradle
src/main/java/com/kuna_backend/controllers/ItemController.java
src/main/java/com/kuna_backend/entities/Item.java
src/main/java/com/kuna_backend/entities/enums/Color.java
src/main/java/com/kuna_backend/entities/enums/Size.java
src/main/java/com/kuna_backend/services/ItemService.java

- Enums modified for Item Model
- Item Entity and Service modifications
- Item Controller with CRUD Methods implemented

T-51 / Rebuilt Item Controller

---

src/main/java/com/kuna_backend/controllers/ClientController.java
src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/entities/Client.java
src/main/java/com/kuna_backend/entities/Order.java
src/main/java/com/kuna_backend/services/ClientService.java
src/main/java/com/kuna_backend/services/OrderService.java

- One to many relationship between Client and Order implemented
- Order Entity and Service modified
- Rebuilt Order Controller with CRUD Methods

T-51 / Rebuilt Order Controller

---

src/main/java/com/kuna_backend/controllers/UserController.java
src/main/java/com/kuna_backend/entities/User.java
src/main/java/com/kuna_backend/services/UserService.java
src/main/resources/application.properties

- Last modifications on User Service and application.properties
- Modifications on User entity (booleans annotations and getters & setters)
- User Controller rebuilt with CRUD Methods

T-51 / Rebuilt User Controller

---

src/main/resources/db/migration/V1.5__Add_order_item_table.sql

- Join table between Order and Item created
- SQL Script succesfully migrated to database with Flyway

Join table between Order and Item 

---

src/main/java/com/kuna_backend/entities/Item.java
src/main/java/com/kuna_backend/entities/Order.java
src/main/resources/db/migration/V1.6__Update_order_item_table.sql

- Join table updated and  quantity_ordered column eliminated
- Implemented many to many relationship between Order and Item entities with JPA
- Defined which entity owns the relationship

T 53 / Implemented Many to Many Relationship between Order and Item

---

src/main/java/com/kuna_backend/controllers/ClientController.java
src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/entities/Client.java
src/main/java/com/kuna_backend/entities/Order.java

- Modifications in Order and Client Entities for implementing one-to-many relationship
- GET all Orders for a Client Endpoint Implemented (in Client controller)
- CREATE a Order for a Specific Client Endpoint Implemented (in Client controller)

T -54/ Get and Create Endpoints for Client - Order relationship 

---

src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/entities/Item.java
src/main/java/com/kuna_backend/entities/Order.java

- Modification on annotation in Item Entity
- Retrieve all Items for an Order Endpoint implemented  / Many-to-many relationship Endpoint
- Create an Item for a specific Order Endpoint implemented / Many-to-many relationship

T-55 / Order Item Endpoints implemented

---

src/main/java/com/kuna_backend/controllers/ClientController.java
src/main/java/com/kuna_backend/controllers/ItemController.java
src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/controllers/UserController.java
src/main/java/com/kuna_backend/entities/Client.java
src/main/java/com/kuna_backend/entities/Item.java
src/main/java/com/kuna_backend/entities/Order.java
src/main/java/com/kuna_backend/entities/User.java
src/main/java/com/kuna_backend/entities/enums/OrderStatus.java
src/main/resources/db/migration/V1.7__Update_order_table.sql

- Order Table Updated and SQL script succesfully migrated with Flyway
- Order Entity modified, new attributes added 
- Enum from Orders created

T- 56 / Refactor Order Table and Entity

---

src/main/java/com/kuna_backend/entities/Client.java
src/main/java/com/kuna_backend/entities/Order.java
src/main/java/com/kuna_backend/entities/Payment.java
src/main/java/com/kuna_backend/entities/enums/PaymentStatus.java

- Payment Entity with relationships created
- PaymentStatus Enum created
- One to Many relationship with Client Implemented
- One to One relationship with Order Implemented

T-58 / Created Payment Entity

---

src/main/java/com/kuna_backend/controllers/PaymentController.java
src/main/java/com/kuna_backend/controllers/UserController.java
src/main/java/com/kuna_backend/entities/Client.java
src/main/java/com/kuna_backend/entities/Order.java
src/main/java/com/kuna_backend/entities/Payment.java
src/main/java/com/kuna_backend/repositories/PaymentRepository.java
src/main/java/com/kuna_backend/services/PaymentService.java

- Payment Repository created
- Payment Service layer created
- Payment Controller with CRUD endpoints created
- Modifications for One to Many and One to One relationships between Payments and Order/Client

T-59 / Payment Api Created

---

build.gradle
src/main/java/com/kuna_backend/controllers/CheckoutController.java
src/main/resources/application.properties

- Add Stripe, Lombok and Thymeleaf dependecies
- Stripe Keys and Base URL added on application properties
- Created Checkout Controller with information for the Checkout form (frontend)

T- 60 / Stripe Checkout

---

src/main/java/com/kuna_backend/entities/ChargeRequest.java
src/main/java/com/kuna_backend/entities/enums/Currency.java

- Created Charge Request Entity
- Created Currency Enum for the Charge operation

T-61 / Created Charge Request Entity 

---

src/main/resources/db/migration/V1.10__Update_order_table.sql
src/main/resources/db/migration/V1.11__Update_payment_table.sql
src/main/resources/db/migration/V1.12__Updat_order_item_table.sql

- Order, Payment and Order_item tables refactores.
- SQL scripts succesfully migrated with Flyway

T-64 / Refactor tables

---

src/main/java/com/kuna_backend/models/AuthenticationToken.java

- Created Authentication Token Entity
- Implemented One to one relationship with Client

T-67 / Created Authentication Token Model

---

build.gradle
src/main/java/com/kuna_backend/controllers/ClientController.java
src/main/java/com/kuna_backend/dtos/ResponseDto.java
src/main/java/com/kuna_backend/dtos/SignupDto.java
src/main/java/com/kuna_backend/exceptions/CustomException.java
src/main/java/com/kuna_backend/exceptions/ExceptionControllerAdvice.java
src/main/java/com/kuna_backend/models/AuthenticationToken.java
src/main/java/com/kuna_backend/models/Client.java
src/main/java/com/kuna_backend/repositories/ClientRepository.java
src/main/java/com/kuna_backend/repositories/TokenRepository.java
src/main/java/com/kuna_backend/services/AuthenticationService.java
src/main/java/com/kuna_backend/services/ClientService.java

- Token Repository and Authentication Service layer created
- Created Sign Up and Response Dto's
- Created some exceptions for Client Authentication
- Created Sign Up Method in Client Service that includes : Exception for existing Client, Encryption of Password, Generation of token for a Client, Save it into the database and response to successful/failed Sign up action. 
- Implemented CREATE/POST Endpoint for Sign Up in Client Controller

T-68 / Sign up Api Implemented 

---

build.gradle
src/main/java/com/kuna_backend/services/ClientService.java

- Refactored Encrypting password method in Client Service
- Added new dependency on build gradle

Modifications on Encryption method

---

src/main/java/com/kuna_backend/controllers/CartController.java
src/main/java/com/kuna_backend/models/Cart.java
src/main/java/com/kuna_backend/repositories/CartRepository.java
src/main/java/com/kuna_backend/services/CartService.java

- Set up of Cart controller, repository, and service
- Created shopping cart model

T-72 / Created Cart model

---

src/main/java/com/kuna_backend/common/ApiResponse.java
src/main/java/com/kuna_backend/controllers/CartController.java
src/main/java/com/kuna_backend/dtos/ItemDto.java
src/main/java/com/kuna_backend/dtos/cart/AddToCartDto.java
src/main/java/com/kuna_backend/dtos/item/ItemDto.java
src/main/java/com/kuna_backend/exceptions/ExceptionControllerAdvice.java
src/main/java/com/kuna_backend/exceptions/ItemNotExistsException.java
src/main/java/com/kuna_backend/models/Item.java
src/main/java/com/kuna_backend/services/CartService.java
src/main/java/com/kuna_backend/services/ItemService.java

Implemented a POST/CREATE endpoint for adding an Item to the shopping cart
- Api Response created
- Implemented Item and AddtoCart Dto's
- Exception of Item doesn't exist created
- Method of Find Item by Id created
- Created Add to Cart method in Cart Service
- Implemented a Post/create endpoint for adding an Item in Cart Controller

T-73  / Implemented Add to Cart Api

---

src/main/java/com/kuna_backend/controllers/CartController.java
src/main/java/com/kuna_backend/dtos/cart/CartItemDto.java
src/main/java/com/kuna_backend/exceptions/CartItemNotExistException.java
src/main/java/com/kuna_backend/repositories/CartRepository.java
src/main/java/com/kuna_backend/services/CartService.java

Created a DELETE endpoint for a Cart item of a Client
- Implemented Delete Cart Item method in Cart Service
- Cart Item dto refactored
- Exception for Cart Item doesn't exist created
- Last modifications on Delete Cart item method and Delete endpoint in Cart controller were made

T-75/ Delete Cart items Api

---

src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/dtos/shipping/ShippingDetailDto.java
src/main/java/com/kuna_backend/models/Client.java
src/main/java/com/kuna_backend/models/Order.java
src/main/java/com/kuna_backend/models/ShippingDetail.java
src/main/java/com/kuna_backend/repositories/ShippingDetailRepository.java
src/main/java/com/kuna_backend/services/ClientService.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/ShippingDetailService.java
src/main/resources/db/migration/V1.20__Update_client_table.sql
src/main/resources/db/migration/V1.21__Add_shipping_detail_table.sql
src/main/resources/db/migration/V1.22__Update_shipping_detail_table.sql

Created Shipping detail  for getting the corresponding data related to the shipping information before placing the Order
- Created Shipping detail Entity and Table in the database
- Refactored Client entity and table
- Implemented relationships between Shipping detail and Client/Order
- Created Shipping detail Dto
- Created Shipping detail repository
- Implemented Add shipping detail method in the Service layer
- Implemented shipping detail method in the Order Endpoint (place_order)

T-81 / Shipping detail

---

src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/controllers/PaymentController.java
src/main/java/com/kuna_backend/models/Order.java
src/main/java/com/kuna_backend/models/Payment.java
src/main/java/com/kuna_backend/models/ShippingDetail.java
src/main/java/com/kuna_backend/repositories/PaymentRepository.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/PaymentService.java
src/main/resources/db/migration/V1.24__Update_shipping_detail_table.sql
src/main/resources/db/migration/V1.25__Update_orders_table.sql
src/main/resources/db/migration/V1.26__Update_orders_table.sql
src/main/resources/db/migration/V1.27__Update_orders_table.sql

- Refactored Place Order method for adding Payment Id into the Order database when Placing the order
- Implemented a retrieve Payment method in the Place Order Endpoint
- Refactored the relationship between Orders and Shipping Detail.
- Implemented one-to-one relationships between Payment and Orders/Shipping detail
- Modifications on Payment repository, service, and controller.

T-83/ Refactor shipping

---

src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/controllers/PaymentController.java
src/main/java/com/kuna_backend/models/Order.java
src/main/java/com/kuna_backend/models/Payment.java
src/main/java/com/kuna_backend/models/ShippingDetail.java
src/main/java/com/kuna_backend/repositories/PaymentRepository.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/PaymentService.java
src/main/resources/db/migration/V1.24__Update_shipping_detail_table.sql
src/main/resources/db/migration/V1.25__Update_orders_table.sql
src/main/resources/db/migration/V1.26__Update_orders_table.sql
src/main/resources/db/migration/V1.27__Update_orders_table.sql

Reverts fiorellamansilla/kuna_backend#49

Revert "T-83/ Refactor shipping"

---

src/main/java/com/kuna_backend/controllers/CartController.java
src/main/java/com/kuna_backend/controllers/ClientController.java
src/main/java/com/kuna_backend/controllers/OrderController.java
src/main/java/com/kuna_backend/controllers/PaymentController.java
src/main/java/com/kuna_backend/controllers/UserController.java
src/main/java/com/kuna_backend/dtos/checkout/StripeResponse.java
src/main/java/com/kuna_backend/enums/Currency.java
src/main/java/com/kuna_backend/enums/PaymentStatus.java
src/main/java/com/kuna_backend/models/AuthenticationToken.java
src/main/java/com/kuna_backend/models/Client.java
src/main/java/com/kuna_backend/models/Item.java
src/main/java/com/kuna_backend/models/Order.java
src/main/java/com/kuna_backend/models/Payment.java
src/main/java/com/kuna_backend/models/ShippingDetail.java
src/main/java/com/kuna_backend/repositories/PaymentRepository.java
src/main/java/com/kuna_backend/services/PaymentService.java
src/main/java/com/kuna_backend/services/ShippingDetailService.java
src/main/resources/db/migration/V1.23__Update_payment_table.sql

Manually fixed some conflicts from T-82 and T-83 old branches

T-85/ fix issues

---

src/main/java/com/kuna_backend/controllers/CategoryController.java
src/main/java/com/kuna_backend/models/Category.java
src/main/java/com/kuna_backend/repositories/CategoryRepository.java
src/main/java/com/kuna_backend/repositories/ProductVariationRepository.java
src/main/java/com/kuna_backend/services/CategoryService.java

- Category Repository created
- Category Service with Create, Read, List and Update Category methods implemented
- Category Controller created : GET, CREATE and UPDATE Endpoints implemented 
- Modification on Category name from Model

T-88 / Category Api

---

src/main/java/com/kuna_backend/controllers/ProductController.java
src/main/java/com/kuna_backend/controllers/ProductVariationController.java
src/main/java/com/kuna_backend/dtos/product/ProductDto.java
src/main/java/com/kuna_backend/dtos/product/ProductVariationDto.java
src/main/java/com/kuna_backend/models/Product.java
src/main/java/com/kuna_backend/models/ProductVariation.java
src/main/java/com/kuna_backend/repositories/ProductVariationRepository.java
src/main/java/com/kuna_backend/services/ProductService.java
src/main/java/com/kuna_backend/services/ProductVariationService.java

Implemented Create Product Variation Api and refactored Product Controller, Service and Dto
- Product Variation Dto created
- Product Variation repository created
- Product Variation Service implemented with create and get methods
- Product Variation Controller with POST endpoint (create product variation) implemented
- Refactored POST endpoint from Product Controller

T-89/ Create product variation api

---

src/main/java/com/kuna_backend/controllers/ProductController.java
src/main/java/com/kuna_backend/controllers/ProductVariationController.java
src/main/java/com/kuna_backend/models/Product.java
src/main/java/com/kuna_backend/services/ProductService.java
src/main/java/com/kuna_backend/services/ProductVariationService.java

- Implemented GET All Product Variations Endpoint in Product Variation Controller and method in Product Variation Service.
- Implemented GET a Product Variation by ID endpoint in Product Variation Controller and method in Product Variation Service.
- Refactored GET All Products Endpoint in Product Controller and Implemented listProducts method in Product Service.
- Implemented Pagination in GET All Products endpoint and in listProducts method in Product Service.

T-90/ GET Product Variation Endpoints & Refactored Product GET Endpoint

---

build.gradle
src/main/java/com/kuna_backend/config/SecurityConfig.java
src/main/java/com/kuna_backend/dtos/client/SignInDto.java
src/main/java/com/kuna_backend/dtos/client/SignupDto.java
src/main/java/com/kuna_backend/models/Client.java
src/main/java/com/kuna_backend/services/ClientService.java
src/test/java/com/kuna_backend/ClientServiceTest.java

Implemented Unit tests for all methods from Client Service

T-92 / Client unit tests

---

src/test/java/com/kuna_backend/AuthenticationServiceTest.java

- Implemented all Unit tests for Authentication Service

T 93/authentication unit tests

---

src/main/java/com/kuna_backend/dtos/product/ProductDto.java
src/main/java/com/kuna_backend/dtos/product/ProductVariationDto.java
src/main/java/com/kuna_backend/models/Product.java
src/main/java/com/kuna_backend/models/ProductVariation.java
src/main/java/com/kuna_backend/services/CategoryService.java
src/test/java/com/kuna_backend/CategoryServiceTest.java
src/test/java/com/kuna_backend/KunaBackendApplicationTests.java
src/test/java/com/kuna_backend/ProductServiceTest.java
src/test/java/com/kuna_backend/ProductVariationServiceTest.java

- Implemented all Unit tests for Product Service
- Implemented all Unit tests for Product  Variation Service
- Implemented all Unit tests for Category Service

T 94/ Products, Product Variations & Category Unit Tests

---

src/main/java/com/kuna_backend/dtos/cart/CartItemDto.java
src/main/java/com/kuna_backend/models/ProductVariation.java
src/main/java/com/kuna_backend/services/CartService.java
src/test/java/com/kuna_backend/CartServiceTest.java

- Implemented all Unit tests for Cart Service methods
- Modifications on Cart Item Dto and Product Variation model
- Modification on Cart Service delete method

T-95/ Cart Unit Tests

---

README.md
build.gradle
src/main/java/com/kuna_backend/controllers/ShippingDetailController.java
src/main/java/com/kuna_backend/dtos/shipping/ShippingDetailDto.java
src/main/java/com/kuna_backend/services/ShippingDetailService.java
src/test/java/com/kuna_backend/ShippingDetailServiceTest.java

- Implemented new GET methods in Shipping Detail Service 
- Created and implemented GET endpoints in Shipping Detail Controller
- Implemented Unit tests for all methods from Shipping Detail Service
- Updated dependencies on Build.gradle
- Created a README file

T-97/ Shipping Detail Unit Tests

---

README.md
src/main/java/com/kuna_backend/dtos/cart/CartDto.java
src/main/java/com/kuna_backend/models/Order.java
src/test/java/com/kuna_backend/OrderItemsServiceTest.java
src/test/java/com/kuna_backend/OrderServiceTest.java
src/test/java/com/kuna_backend/builders/OrderTestDataBuilder.java

- Implemented Unit test for methods from Order Item Service
- Implemented Test Data Builders for the Order Service Test as a way to reduce duplication of Objects creation code
- Implemented Unit tests for all methods from the Order Service

T-98 / Orders Unit Tests

---

README.md
src/main/java/com/kuna_backend/models/Order.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/resources/data.sql
src/main/resources/db/migration/V1.39__Drop_users_table.sql

- Implemented method in Order Model & Service for generating a random tracking number every time an order is placed.
- Created a SQL file with test data
- Modification on READ ME file

T-100/ Tracking number Auto-generation & Test data File

---

src/main/java/com/kuna_backend/services/OrderService.java

Implemented a method in Order Service for updating the Product Variation Quantity Stock everytime an Order is placed

T-101 / Quantity stock Updating

---

src/main/resources/db/migration/V1.29__Update_item_table.sql
src/main/resources/db/migration/V1.33__Update_order_item_table.sql

Flyway migration is missing statements

Fix flyway migration

---

src/main/java/com/kuna_backend/dtos/cart/CartItemDto.java
src/main/java/com/kuna_backend/dtos/product/ProductVariationDto.java
src/main/java/com/kuna_backend/models/Product.java
src/main/java/com/kuna_backend/models/ProductVariation.java
src/main/java/com/kuna_backend/services/ProductService.java
src/main/java/com/kuna_backend/services/ProductVariationService.java

- Implemented a method to create the Product Variation which is assigned to a specific Product when updating it. This way, the admin can create a Product first (with its basic attributes) and then create the Product Variation during the Product's update. 
- Eliminated methods from the Product Variation Service because of its association with the Product. The methods for creating and updating a Product Variation are implemented in the Product Service layer.
- Implemented a method to update only the attributes from the Product Variation. This way, the admin can constatly update the quantity stock of a Product.
- Implemented a method to update only the attributes from the Product.

T-102 / Product service refactored

---

src/main/java/com/kuna_backend/controllers/ProductController.java
src/main/java/com/kuna_backend/controllers/ProductVariationController.java
src/main/java/com/kuna_backend/models/ProductVariation.java
src/main/java/com/kuna_backend/repositories/CategoryRepository.java
src/main/java/com/kuna_backend/repositories/ProductRepository.java
src/main/java/com/kuna_backend/services/ProductService.java
src/main/java/com/kuna_backend/services/ProductVariationService.java
src/test/java/com/kuna_backend/OrderServiceTest.java
src/test/java/com/kuna_backend/ProductServiceTest.java
src/test/java/com/kuna_backend/ProductVariationServiceTest.java
src/test/java/com/kuna_backend/builders/OrderTestDataBuilder.java

- Multiple changes on Product Controller, Product Repository, Product Service and Product Service tests in order to include the new methods for creating a Product Variation for a specific Product and retrieving a Product with its Variations.

T-103/ ProductVariation_fixes

---

src/main/java/com/kuna_backend/common/ApiResponse.java
src/main/java/com/kuna_backend/controllers/ProductController.java
src/main/java/com/kuna_backend/models/Product.java
src/main/java/com/kuna_backend/models/ProductVariation.java
src/main/java/com/kuna_backend/services/ProductService.java
src/test/java/com/kuna_backend/ProductControllerTest.java
src/test/java/com/kuna_backend/ProductServiceTest.java

- Changes on Product Controller endpoints & ApiResponse class
- Implemented tests fo the Product Controller endpoints

T-104 / Product controller tests & changes

---

src/main/java/com/kuna_backend/controllers/ProductVariationController.java
src/main/java/com/kuna_backend/dtos/product/ProductVariationDto.java
src/main/java/com/kuna_backend/services/ProductVariationService.java
src/test/java/com/kuna_backend/ProductControllerTest.java
src/test/java/com/kuna_backend/ProductServiceTest.java
src/test/java/com/kuna_backend/ProductVariationControllerTest.java
src/test/java/com/kuna_backend/ProductVariationServiceTest.java

- Refactored methods in ProductVariation Controller, Dto & Service layers
- Implemented new tests for this changes & the ProductVariation Controller

T -105 / ProductVariation changes & tests

---

src/main/java/com/kuna_backend/controllers/ShippingDetailController.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/ShippingDetailService.java
src/test/java/com/kuna_backend/OrderServiceTest.java
src/test/java/com/kuna_backend/ShippingDetailServiceTest.java

- Implemented changes in Shipping Detail service and controller for creating a new Shipping Detail entity only for a new Client.
- If the Client already exists, then the existing Shipping detail is retrieved from the repository and can only be updated.
- Refactored the placeOrder method and endpoint according to this logic. 
- Refactored Shipping Detail service and Order service tests.

T-112 / Refactored Shipping Detail

---

src/main/java/com/kuna_backend/services/AuthenticationService.java
src/main/java/com/kuna_backend/services/CategoryService.java
src/main/java/com/kuna_backend/services/ClientService.java
src/test/java/com/kuna_backend/AuthenticationServiceTest.java
src/test/java/com/kuna_backend/CategoryServiceTest.java
src/test/java/com/kuna_backend/ClientServiceTest.java
src/test/java/com/kuna_backend/ProductControllerTest.java
src/test/java/com/kuna_backend/ProductServiceTest.java
src/test/java/com/kuna_backend/builders/ProductTestDataBuilder.java

- Refactored tests for improving readability and avoiding code duplication.
- Implemented a Product Data Builder for Product tests.

T-113/ Refactored tests (first part)

---

src/main/java/com/kuna_backend/services/CartService.java
src/main/java/com/kuna_backend/services/OrderItemsService.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/ProductService.java
src/main/java/com/kuna_backend/services/ShippingDetailService.java
src/test/java/com/kuna_backend/PaymentServiceTest.java

- Implemented a Constructor with the dependencies as parameters.
- And changed the position of the Autowired annotation for some Services.

T - 114 / Service improvement

---

src/main/java/com/kuna_backend/services/CartService.java
src/main/java/com/kuna_backend/services/OrderItemsService.java
src/main/java/com/kuna_backend/services/OrderService.java
src/main/java/com/kuna_backend/services/ProductService.java
src/main/java/com/kuna_backend/services/ShippingDetailService.java
src/test/java/com/kuna_backend/CartServiceTest.java
src/test/java/com/kuna_backend/ClientServiceTest.java
src/test/java/com/kuna_backend/OrderItemsServiceTest.java
src/test/java/com/kuna_backend/OrderServiceTest.java
src/test/java/com/kuna_backend/PaymentServiceTest.java
src/test/java/com/kuna_backend/ProductVariationControllerTest.java
src/test/java/com/kuna_backend/ProductVariationServiceTest.java
src/test/java/com/kuna_backend/ShippingDetailServiceTest.java
src/test/java/com/kuna_backend/builders/CartTestDataBuilder.java
src/test/java/com/kuna_backend/builders/ClientTestDataBuilder.java
src/test/java/com/kuna_backend/builders/PaymentTestDataBuilder.java
src/test/java/com/kuna_backend/builders/ProductVariationTestDataBuilder.java
src/test/java/com/kuna_backend/builders/ShippingTestDataBuilder.java

- Implemented Data Builders for avoiding code duplication on tests.
- Improved ProductVariation, OrderItem, Shippingdetail, Client, Cart, Order and Payment tests.

T-115/ Refactored tests (second part)
